apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: {{ .Values.redis.namespace }}
  labels:
    app: redis
    component: redis
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
  selector:
    app: redis
    component: redis
