
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-kubeflow-user-workspace
  labels:
    service-pvname: service-kubeflow-user-workspace
spec:
  capacity:
    storage: {{ .Values.cube.persistence.serviceWorkspace.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/k8s/kubeflow/pipeline/workspace
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-user-workspace
  namespace: service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.cube.persistence.serviceWorkspace.size }}
#  selector:
#    matchLabels:
#      service-pvname: service-kubeflow-user-workspace
  storageClassName: ""
  volumeName: service-kubeflow-user-workspace

# 模型归档
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-kubeflow-archives
  labels:
    service-pvname: service-kubeflow-archives
spec:
  capacity:
    storage: {{ .Values.cube.persistence.serviceArchives.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/k8s/kubeflow/pipeline/archives
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-archives
  namespace: service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.cube.persistence.serviceArchives.size }}
#  selector:
#    matchLabels:
#      service-pvname: service-kubeflow-archives
  storageClassName: ""
  volumeName: service-kubeflow-archives

