apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: infra-kubeflow-dashboard
  namespace: {{ .Values.cube.namespace }}
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - "{{ .Values.host }}"    # 管理平台的域名   kubeflow.local.com
  http:
  - route:
    - destination:
        host: kubeflow-dashboard-frontend.{{ .Values.cube.namespace }}.svc.cluster.local
        port:
          number: 80
