kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: {{ .Values.mysql.namespace }}
  labels:
    app: mysql
    component: mysql
spec:
  ports:
    - name: tcp
      port: {{ .Values.mysql.port }}
      targetPort: 3306
  selector:
    app: mysql
    component: mysql