global:
  # -- Global Docker image registry.
  imageRegistry: "10.20.2.3:5000/cube-studio"
  # -- Global Docker registry secret names as an array.
  imagePullSecrets: []
  # -- Global storageClass for Persistent Volume(s).
  storageClass: "local-path"

argo:
  enable: true
  namespace: kubeflow
  piplineNamespace: pipeline
  image: argoproj/workflow-controller:v3.4.3
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /healthz
      port: 6060
    initialDelaySeconds: 90
    periodSeconds: 60
    timeoutSeconds: 30
  readinessProbe: {}
  minio:
    image: minio/minio:RELEASE.2023-04-20T17-56-55Z
    root: minio
    password: minio123
    persistence:
      enabled: true
      storageClass: ""
      size: 5Gi #500

kubeflow:
  namespace: kubeflow
  trainingOperator:
    image: kubeflow/training-operator:v1-855e096